# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0004_auto_20170221_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crontabschedule',
            options={'ordering': ['month_of_year', 'day_of_month', 'day_of_week', 'hour', 'minute', 'timezone'], 'verbose_name': 'crontab', 'verbose_name_plural': 'crontabs'},
        ),
        migrations.AddField(
            model_name='crontabschedule',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
        migrations.AlterField(
            model_name='solarschedule',
            name='event',
            field=models.CharField(choices=[('dawn_civil', 'dawn_civil'), ('sunrise', 'sunrise'), ('dawn_nautical', 'dawn_nautical'), ('dusk_civil', 'dusk_civil'), ('dusk_nautical', 'dusk_nautical'), ('dusk_astronomical', 'dusk_astronomical'), ('sunset', 'sunset'), ('solar_noon', 'solar_noon'), ('dawn_astronomical', 'dawn_astronomical')], max_length=24, verbose_name='event'),
        ),
    ]
