# Generated by Django 2.0.6 on 2018-10-22 05:20
from __future__ import absolute_import, unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_celery_beat', '0005_add_solarschedule_events_choices_squashed_0009_merge_20181012_1416'), # noqa
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='priority',
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[django.core.validators.MaxValueValidator(255)],
                verbose_name='priority'),
        ),
    ]
