# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0005_auto_20171121_1131'),
        ('django_celery_beat', '0005_add_solarschedule_events_choices'),
    ]

    operations = [
    ]
