# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 08:28
from __future__ import absolute_import, unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0005_add_solarschedule_events_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crontabschedule',
            options={'ordering': ['month_of_year', 'day_of_month', 'day_of_week', 'hour', 'minute', 'timezone'], 'verbose_name': 'crontab', 'verbose_name_plural': 'crontabs'},
        ),
        migrations.AddField(
            model_name='crontabschedule',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
