# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:00
from __future__ import absolute_import, nicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_auto_20180131_0028'),
        ('django_celery_beat', '0006_auto_20180210_1226'),
    ]

    operations = [
    ]
