# Generated by Django 2.1.2 on 2018-10-12 14:16
from __future__ import absolute_import, unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0007_auto_20181012_1414'),
        ('django_celery_beat', '0008_auto_20180914_1922'),
    ]

    operations = [
    ]
