# Generated by Django 2.2.2 on 2019-06-15 17:06

from __future__ import absolute_import, unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockedschedule',
            name='clocked_time',
            field=models.DateTimeField(
                help_text='Run the task at clocked time', unique=True,
                verbose_name='Clock Time'),
        ),
        migrations.AlterUniqueTogether(
            name='crontabschedule',
            unique_together={('minute', 'hour', 'day_of_week', 'day_of_month',
                              'month_of_year', 'timezone')},
        ),
        migrations.AlterUniqueTogether(
            name='intervalschedule',
            unique_together={('every', 'period')},
        ),
    ]
