# Generated by Django 2.2.16 on 2020-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0014_remove_clockedschedule_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='task_signature',
            field=models.BinaryField(help_text='Serialized signature objects of task (or chain, group, etc.) got by https://pypi.org/project/dill/', null=True),
        ),
    ]
