# Generated by Django 3.1.7 on 2021-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontabschedule',
            name='name',
            field=models.CharField(blank=True, help_text='Short Description For This Cron Schedule', max_length=200, null=True, verbose_name='Name'),
        ),
    ]
