# Generated by Django 2.2.16 on 2020-09-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_periodictask_task_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='callback_signature',
            field=models.BinaryField(help_text="Serialized `celery.canvas.Signature` type's callback task got by https://pypi.org/project/dill/ (use as link arg in `.apply_async` method)", null=True),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='callback_signature_sign',
            field=models.CharField(help_text="Signature (in hex) of serialized `celery.canvas.Signature` type's callback task (see callback_signature field)", max_length=1028, null=True),
        ),
    ]
