# Generated by Django 3.2 on 2021-04-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('django_celery_beat', '0016_auto_20200903_1356'),
    ]

    operations = [
    ]
