# Generated by Django 5.2.15 on 2026-07-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="clockedschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="crontabschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="intervalschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="solarschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddIndex(
            model_name="clockedschedule",
            index=models.Index(
                fields=["updated_at"], name="django_cele_updated_20a5a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crontabschedule",
            index=models.Index(
                fields=["updated_at"], name="django_cele_updated_6e55f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervalschedule",
            index=models.Index(
                fields=["updated_at"], name="django_cele_updated_63e080_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="periodictask",
            index=models.Index(
                fields=["date_changed"], name="django_cele_date_ch_48a1e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solarschedule",
            index=models.Index(
                fields=["updated_at"], name="django_cele_updated_2f98b6_idx"
            ),
        ),
    ]
