# Generated by Django 5.2.9 on 2025-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clockedschedule",
            name="clocked_time",
            field=models.DateTimeField(
                help_text="Run the task at clocked time",
                unique=True,
                verbose_name="Clock Time",
            ),
        ),
        migrations.AddConstraint(
            model_name="crontabschedule",
            constraint=models.UniqueConstraint(
                fields=(
                    "minute",
                    "hour",
                    "day_of_month",
                    "month_of_year",
                    "day_of_week",
                    "timezone",
                ),
                name="unique_crontab",
            ),
        ),
        migrations.AddConstraint(
            model_name="intervalschedule",
            constraint=models.UniqueConstraint(
                fields=("every", "period"), name="unique_interval"
            ),
        ),
    ]
