# Generated by Django 6.0.7 on 2026-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='periodictask',
            index=models.Index(fields=['enabled'], name='beat_periodic_enabled_idx'),
        ),
    ]
