# Generated by Django 5.2.4 on 2025-07-31 11:48

import django_celery_beat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crontabschedule",
            name="day_of_week",
            field=models.CharField(
                default="*",
                help_text='Cron Days Of The Week to Run. Use "*" for "all", Sunday is 0, Monday is 1. (Example: "0,5")',
                max_length=64,
                validators=[django_celery_beat.validators.day_of_week_validator],
                verbose_name="Day(s) Of The Week",
            ),
        ),
    ]
