# Generated by Django 5.0.1 on 2026-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="periodictasks",
            old_name="last_update",
            new_name="last_change_marker",
        ),
        migrations.AddField(
            model_name="clockedschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="crontabschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="intervalschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AddField(
            model_name="solarschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, null=True, verbose_name="Last Modified"
            ),
        ),
        migrations.AlterField(
            model_name="periodictask",
            name="date_changed",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Datetime that this PeriodicTask was last modified",
                verbose_name="Last Modified",
            ),
        ),
    ]
