# Generated by Django 6.1.1 on 2026-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0020_periodictask_beat_periodic_enabled_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodictask',
            name='options',
            field=models.TextField(blank=True, default='{}', help_text='JSON encoded additional execution options for the task (Example: {"MessageGroupId": "my_group"}).', verbose_name='Additional Options'),
        ),
    ]
