version: 0.2

env:
  variables:
    PIP_REPO: 'pip.test.singleplatform.co'

phases:
  install:
    commands:
      - pip config set global.index-url https://$PIP_REPO/simple
      - pip config set global.trusted-host $PIP_REPO
  build:
    commands:
      - python setup.py check
      # python setup.py test
      - python setup.py sdist
      - python setup.py bdist_wheel
  post_build:
    commands:
      - piprepo sync dist s3://$PIP_REPO

