# Copyright (C) 2020-2030 Asif Saif Uddin <auvipy@gmail.com> and all contributors.
# Copyright (C) 2019 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the BSD License (3 clause, also known as the new BSD license)

ARG COMPOSE_PROJECT_NAME=django-celery-beat
FROM ${COMPOSE_PROJECT_NAME}_base

COPY docker/celery-beat/entrypoint.sh  /app/docker/celery-beat/
