name: Build & Publish to PyPI

on:
  workflow_dispatch:
  # Ensure the build works on main
  push:
    branches: [main]
    tags: ['*']
  # Ensure the build works on each pull request
  pull_request:

permissions: {}

jobs:
  build:
    name: Build distribution
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.x"
    
    - name: Install pypa/build
      run: python3 -m pip install build --user
    
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    
    - name: Store the distribution packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: blacksmith-4vcpu-ubuntu-2204

    needs: [build]

    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    
    environment:
      name: pypi
      url: https://pypi.org/p/django-celery-beat
    
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2

  github-release:
    name: Upload them to GitHub Release
    runs-on: blacksmith-4vcpu-ubuntu-2204

    needs: [publish-to-pypi]

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${GITHUB_REF_NAME}'
          --repo '${{ github.repository }}'
          --notes ""
      
      - name: Upload artifact to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload
          '${GITHUB_REF_NAME}' dist/**
          --repo '${{ github.repository }}'
